---

- name: Install EPEL repo.
  shell: yum --enablerepo=extras install epel-release -y

- name: Ensure required packages are installed
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ yum_packages }}"

- name: net.ipv4.ip_forward=1
  shell: sysctl -w net.ipv4.ip_forward=1
